version: '2'
services:
  transform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transform
    ports:
     - "4040:4040"
    volumes:
     - "./scripts:/root/scripts"
     - "/mnt/bs3/graphsense_spark/:/spark_store/"
    environment:
     - CASSANDRA_HOST=cassandra
    networks:
     - graphsense-global-net
networks:
  graphsense-global-net:
    external: true
